<?php

require_once dirname(__FILE__) . '/../../../curation_tool.inc';
require_once dirname(__FILE__) . '/../../../classes/exceptions/InvalidIDTokenException.php';

/**
 * Test class for InvalidIDTokenException.
 * Generated by PHPUnit on 2012-03-28 at 22:43:40.
 */
class InvalidIDTokenExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var InvalidIDTokenException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    print 'setting up test.';
    $message = 'test';
    $this->object = new InvalidIDTokenException($message);
    print 'object created';
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * 
   */
  public function testConstruct() {
    print '===============Invoking '.__METHOD__.'==============';
    $this->assertTrue(TRUE);
  }

}

?>
