<?php

require_once dirname(__FILE__) . '/../../../classes/exceptions/PathNotFoundException.php';

/**
 * Test class for PathNotFoundException.
 * Generated by PHPUnit on 2011-10-25 at 19:07:04.
 */
class PathNotFoundExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var PathNotFoundException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new PathNotFoundException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
