<?php

require_once dirname(__FILE__) . '/../../../classes/exceptions/XFDUException.php';

/**
 * Test class for XFDUException.
 * Generated by PHPUnit on 2012-03-28 at 22:58:03.
 */
class XFDUExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $message = 'test';
    $this->object = new XFDUException($message);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * 
   */
  public function testConstruct() {
    $this->assertNotEmpty($this->object->getMessage());
  }

}

?>
