<?php

require_once dirname(__FILE__) . '/../../../classes/schemas/aXMLElement.php';

/**
 * Test class for aXMLElement.
 * Generated by PHPUnit on 2011-11-05 at 03:07:04.
 */
class aXMLElementTest extends PHPUnit_Framework_TestCase {

  /**
   * @var aXMLElement
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new aXMLElement;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }
  
  /**
   * 
   */
  public function testValidID() {
    $this->assertTrue($this->object->validate_id('validID'));
  }
  
  public function testInvalidID() {
    $this->assertFalse($this->object->validate_id('0badID'));
  }

}

?>
