<?php

require_once dirname(__FILE__) . '/../../../classes/schemas/aXMLElement.php';

/**
 * Test class for aXMLElement.
 * Generated by PHPUnit on 2011-11-05 at 03:07:04.
 */
class aXMLElementTest extends PHPUnit_Framework_TestCase {

  /**
   * @var aXMLElement
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new aXMLElement;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }
  
  /**
   * 
   */
  public function testValidID() {
    $this->assertTrue($this->object->validate_id('validID'));
  }
  
  /**
   * 
   */
  public function testInvalidID() {
    $this->assertFalse($this->object->validate_id('0badID'));
  }
  
  public function testAttribute() {
    $this->assertFalse($this->object->isset_attributes());
    
    $name1 = 'attone';
    $name2 = 'atttwo';
    $value1 = 'val1';
    $value2 = 'val2';
    
    $this->object->add_attribute($name1, $value1);
    $this->object->add_attribute($name2, $value2);
    $atts = $this->object->get_attributes();
    
    $this->assertTrue($this->object->isset_attributes());
    $this->assertEquals(2, sizeof($atts));
    $this->assertEquals($value1, $atts[$name1]);
    $this->assertEquals($value2, $this->object->get_attribute($name2));
    $this->assertFalse($this->object->get_attribute('invalid'));
    
    $this->object->unset_attributes();
    
    $this->assertFalse($this->object->isset_attributes());
  }

}

?>
