<?php

require_once dirname(__FILE__) . '/../../../classes/schemas/DummySchema.php';

/**
 * Test class for DummySchema.
 * Generated by PHPUnit on 2011-11-05 at 03:07:07.
 */
class DummySchemaTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DummySchema
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DummySchema;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
