<?php
require_once dirname(__FILE__) . '/../../../curation_tool.inc';

/**
 * Test class for XMLElement.
 * Generated by PHPUnit on 2011-11-14 at 23:08:37.
 */
class XMLElementTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XMLElement
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XMLElement;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testName() {
    $this->assertFalse($this->object->isset_name());
    
    $value = 'test';
    $this->object->set_name($value);
    
    $this->assertTrue($this->object->isset_name());
    $this->assertEquals($value, $this->object->get_name());
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testInvalidName() {
    $this->object->set_name('xmlInvalid');
  }

  /**
   * 
   */
  public function testValue() {
    $this->assertFalse($this->object->isset_value());
    
    $value = 'test';
    $this->object->set_value($value);
    
    $this->assertTrue($this->object->isset_value());
    $this->assertEquals($value, $this->object->get_value());
  }
  
  public function testChildren() {
    $this->assertFalse($this->object->isset_children());
    
    $child1 = new XMLElement('child1');
    $child2 = new XMLElement('child2');
    
    $this->object->append_child($child1);
    $this->assertTrue($this->object->isset_children());
    $this->assertEquals(1, sizeof($this->object->get_children()));
    
    $this->object->append_child($child2);
    $this->assertEquals(2, sizeof($this->object->get_children()));
    
    $this->object->append_child($child1);
    $this->assertEquals(2, sizeof($this->object->get_children()));
    
    $this->object->remove_child($child1);
    $this->assertEquals(1, sizeof($this->object->get_children()));
    
  }
}

?>