<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for BehaviorSection.
 * Generated by PHPUnit on 2011-11-07 at 18:41:14.
 */
class BehaviorSectionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var BehaviorSection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new BehaviorSection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testAdd_behaviorObject() {
    $this->assertFalse($this->object->isset_behaviorObjects());
    
    $value = new BehaviorObject();
    $this->object->add_behaviorObject($value);
    $this->object->add_behaviorObject($value);
    $objs = $this->object->get_behaviorObjects();
    
    $this->assertTrue($this->object->isset_behaviorObjects());
    $this->assertEquals(2, sizeof($objs));
    $this->assertEquals(get_class($value), get_class($objs[0]));
    
    $this->object->unset_behaviorObjects();
    $this->assertFalse($this->object->isset_behaviorObjects());
  }

}

?>
