<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for ChecksumInformation.
 * Generated by PHPUnit on 2011-11-07 at 23:54:48.
 */
class ChecksumInformationTest extends PHPUnit_Framework_TestCase {

  /**
   * @var ChecksumInformation
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new ChecksumInformation;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testChecksumName() {
    $this->assertFalse($this->object->isset_checksumName());
    
    $value = 'test';
    $this->object->set_checksumName($value);
    $this->assertTrue($this->object->isset_checksumName());
    $this->assertEquals($value, $this->object->get_checksumName());
  }

  /**
   * 
   */
  public function testValue() {
    $this->assertFalse($this->object->isset_value());
    
    $value = 'test';
    $this->object->set_value($value);
    $this->assertTrue($this->object->isset_value());
    $this->assertEquals($value, $this->object->get_value());
  }

}

?>
