<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/ContentUnit.php';

/**
 * Test class for ContentUnit.
 * Generated by PHPUnit on 2011-11-04 at 21:48:51.
 */
class ContentUnitTest extends PHPUnit_Framework_TestCase {

  /**
   * @var ContentUnit
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new ContentUnit;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * 
   */
  public function testAbstractContentUnit() {
    $this->assertFalse($this->object->isset_abstractContentUnit());
    $this->assertEmpty($this->object->get_abstractContentUnit());
  }

  public function testAnyMdID() {
    $this->assertFalse($this->object->isset_anyMdID());

    $anyMdID = 'test';
    $this->object->set_anyMdID($anyMdID);
    $this->assertTrue($this->object->isset_anyMdID());
    $this->assertEquals($anyMdID, $this->object->get_anyMdID());
  }

}

?>
