<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for DataObjectPointer.
 * Generated by PHPUnit on 2011-11-05 at 03:07:15.
 */
class DataObjectPointerTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DataObjectPointer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DataObjectPointer;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * Tests dataObjectID
   */
  public function testDataObjectID() {
    $this->assertFalse($this->object->isset_dataObjectID());
    
    $dataObjectID = 'test';
    $this->object->set_dataObjectID($dataObjectID);
    $this->assertTrue($this->object->isset_dataObjectID());
    $this->assertEquals($dataObjectID, $this->object->get_dataObjectID());
  }
  
  /**
   * Tests ID
   */
  public function testID() {
    $this->assertFalse($this->object->isset_id());
    
    $id = 'test';
    $this->object->set_id($id);
    $this->assertTrue($this->object->isset_id());
    $this->assertEquals($id, $this->object->get_id());
  }

}

?>
