<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/DataObjectSection.php';

/**
 * Test class for DataObjectSection.
 * Generated by PHPUnit on 2011-11-08 at 04:30:24.
 */
class DataObjectSectionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DataObjectSection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DataObjectSection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testDataObject() {
    $this->assertFalse($this->object->isset_dataObjects());
    
    $value = new DataObject();
    $this->object->add_dataObject($value);
    $this->object->add_dataObject($value);
    
    $this->assertTrue($this->object->isset_dataObjects());
    $objs = $this->object->get_dataObjects();
    $this->assertEquals(2, sizeof($objs));
    $this->assertEquals(get_class($value), get_class($objs[0]));
    
    $this->object->unset_dataObjects();
    $this->assertFalse($this->object->isset_dataObjects());
    
  }

}

?>
