<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for EnvironmentInfo.
 * Generated by PHPUnit on 2011-11-05 at 03:07:12.
 */
class EnvironmentInfoTest extends PHPUnit_Framework_TestCase {

  /**
   * @var EnvironmentInfo
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new EnvironmentInfo;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * 
   */
  public function testExtension() {
    $this->assertFalse($this->object->isset_extension());
    
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $anyXML = $dom->createElement('stuff');
    $anyXML->setAttribute('xmlns:pre', 'example.com');
    
    $extension = new Extension();
    $extension->set_any($anyXML);
    
    $expected = $dom->createElement('extension');
    $expected->appendChild($anyXML);
    
    $this->object->set_extension($extension);
    
    $this->assertTrue($this->object->isset_extension());
    $this->assertEquals('Extension', get_class($this->object->get_extension()));
    $this->assertEquals($expected, $dom->importNode($this->object->get_extension()->get_any()));
  }
  
  /**
   * 
   */
  public function testXMLData() {
    $this->assertFalse($this->object->isset_xmlData());
    
    $value = 'test';
    $this->object->set_xmlData($value);
    
    $this->assertTrue($this->object->isset_xmlData());
    $this->assertEquals($value, $this->object->get_xmlData());
  }
  
  /**
   * 
   */
  public function testGet_as_DOM() {    
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $expectedElement = $dom->createElement('environmentInfo');
    
    $expectedElement->appendChild($xmlData = $dom->createElement('xmlData'));
    $xmlData->appendChild($dom->createElement('stuff'));
    
    $xmlData = new XMLData();
    $xmlData->set_any($dom->createElement('stuff'));
    $this->object->set_xmlData($xmlData);
    
    $this->assertEqualXMLStructure($expectedElement, $this->object->get_as_DOM());
  }

}

?>
