<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for FileContent.
 * Generated by PHPUnit on 2011-11-07 at 06:06:09.
 */
class FileContentTest extends PHPUnit_Framework_TestCase {

  /**
   * @var FileContent
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new FileContent;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @todo Implement testSet_binaryData().
   */
  public function testBinaryData() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }
  
  /**
   * @expectedException UnimplementedMethodException
   */
  public function testUnimplementedSetBinary() {
    $this->object->set_binaryData('test');
  }
  
  /**
   * @expectedException UnimplementedMethodException
   */
  public function testUnimplementedGetBinary() {
    $this->object->get_binaryData();
  }

  /**
   * 
   */
  public function testID() {
    $this->assertFalse($this->object->isset_id());
    
    $value = 'test';
    $this->object->set_id($value);
    $this->assertTrue($this->object->isset_id());
    $this->assertEquals($value, $this->object->get_id());
  }

  /**
   * 
   */
  public function testXMLData() {
    $this->assertFalse($this->object->isset_XMLData());
    
    $value = new XMLData();
    $this->object->set_XMLData($value);
    $this->assertTrue($this->object->isset_XMLData());
    $this->assertEquals('XMLData', get_class($this->object->get_XMLData()));
  }

}

?>
