<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/InputParameter.php';

/**
 * Test class for InputParameter.
 * Generated by PHPUnit on 2011-11-08 at 06:46:56.
 */
class InputParameterTest extends PHPUnit_Framework_TestCase {

  /**
   * @var InputParameter
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new InputParameter;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testContent() {
    $this->assertFalse($this->object->isset_content());
    
    $value = new DataObjectPointer();
    $this->object->set_content($value);
    
    $this->assertTrue($this->object->isset_content());
    $this->assertEquals(get_class($value), get_class($this->object->get_content()));
  }

  /**
   * 
   */
  public function testName() {
    $this->assertFalse($this->object->isset_name());
    
    $value = 'test';
    $this->object->set_name($value);
    
    $this->assertTrue($this->object->isset_name());
    $this->assertEquals($value, $this->object->get_name());
  }

  /**
   * 
   */
  public function testValue() {
    $this->assertFalse($this->object->isset_value());
    
    $value = 'test';
    $this->object->set_value($value);
    
    $this->assertTrue($this->object->isset_value());
    $this->assertEquals($value, $this->object->get_value());
  }

}

?>
