<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for InterfaceDefinition.
 * Generated by PHPUnit on 2011-11-08 at 06:54:14.
 */
class InterfaceDefinitionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var InterfaceDefinition
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new InterfaceDefinition;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testInputParameter() {
    $this->assertFalse($this->object->isset_inputParameters());
    
    $value = new InputParameter();
    $this->object->add_inputParameter($value);
    $this->object->add_inputParameter($value);
    $objs = $this->object->get_inputParameters();
    
    $this->assertTrue($this->object->isset_inputParameters());
    $this->assertEquals(2, sizeof($objs));
    $this->assertEquals(get_class($value), get_class($objs[0]));
    
    $this->object->unset_inputParameters();
    $this->assertFalse($this->object->isset_inputParameters());
  }

}

?>
