<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/KeyDerivation.php';

/**
 * Test class for KeyDerivation.
 * Generated by PHPUnit on 2011-11-08 at 18:37:15.
 */
class KeyDerivationTest extends PHPUnit_Framework_TestCase {

  /**
   * @var KeyDerivation
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new KeyDerivation;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * 
   */
  public function testIterationCount() {
    $this->assertFalse($this->object->isset_iterationCount());

    $value = 100;
    $this->object->set_iterationCount($value);

    $this->assertTrue($this->object->isset_iterationCount());
    $this->assertEquals($value, $this->object->get_iterationCount());
  }

  /**
   * @expectedException VariableTypeException
   */
  public function testBadIterationCount() {
    $this->object->set_iterationCount('bad');
  }

  /**
   *
   */
  public function testName() {
    $this->assertFalse($this->object->isset_name());

    $value = 'name';
    $this->object->set_name($value);

    $this->assertTrue($this->object->isset_name());
    $this->assertEquals($value, $this->object->get_name());
  }

  /**
   *
   */
  public function testSalt() {
    $this->assertFalse($this->object->isset_salt());

    $value = 'test';
    $this->object->set_salt($value);

    $this->assertTrue($this->object->isset_salt());
    $this->assertEquals($value, $this->object->get_salt());
  }
}

?>
