<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/MetadataSection.php';

/**
 * Test class for MetadataSection.
 * Generated by PHPUnit on 2011-11-09 at 04:12:58.
 */
class MetadataSectionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetadataSection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetadataSection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @todo Implement testAdd_metadataObject().
   */
  public function testMetadataObject() {
    $this->assertFalse($this->object->isset_metadataObjects());
    
    $value = new MetadataObject();
    $this->object->add_metadataObject($value);
    $this->object->add_metadataObject($value);
    $objs = $this->object->get_metadataObjects();
    
    $this->assertTrue($this->object->isset_metadataObjects());
    $this->assertEquals(2, sizeof($objs));
    $this->assertEquals(get_class($value), get_class($objs[0]));
    
    $this->object->unset_metadataObjects();
    
    $this->assertFalse($this->object->isset_metadataObjects());
  }

}

?>
