<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for MetadataWrap.
 * Generated by PHPUnit on 2011-11-07 at 17:05:40.
 */
class MetadataWrapTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetadataWrap
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetadataWrap;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testMimeType() {
    $this->assertFalse($this->object->isset_mimeType());
    
    $value = 'test';
    $this->object->set_mimeType($value);
    $this->assertTrue($this->object->isset_mimeType());
    $this->assertEquals($value, $this->object->get_mimeType());
  }

  /**
   * 
   */
  public function testTextInfo() {
    $this->assertFalse($this->object->isset_textInfo());
    
    $value = 'test';
    $this->object->set_textInfo($value);
    $this->assertTrue($this->object->isset_textInfo());
    $this->assertEquals($value, $this->object->get_textInfo());
  }

  /**
   * 
   */
  public function testVocabularyName() {
    $this->assertFalse($this->object->isset_vocabularyName());
    
    $value = 'test';
    $this->object->set_vocabularyName($value);
    $this->assertTrue($this->object->isset_vocabularyName());
    $this->assertEquals($value, $this->object->get_vocabularyName());
  }

}

?>
