<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for MetaDataSection.
 * Generated by PHPUnit on 2011-11-07 at 17:33:07.
 */
class MetaDataSectionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetaDataSection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetaDataSection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testAdd_metadataObject() {
    $this->assertFalse($this->object->isset_metadataObjects());
    
    $value = new MetadataObject();
    $this->object->add_metadataObject($value);
    $this->assertTrue($this->object->isset_metadataObjects());
    $this->assertEquals(1, sizeof($this->object->get_metadataObjects()));
    $this->object->add_metadataObject($value);
    $this->assertTrue($this->object->isset_metadataObjects());
    $this->assertEquals(2, sizeof($this->object->get_metadataObjects()));
    
    $objects = $this->object->get_metadataObjects();
    $object = $objects[0];
    $this->assertEquals(get_class($value), get_class($object));
    
    $this->object->unset_metadataObject();
    $this->assertFalse($this->object->isset_metadataObjects());
  }

}

?>
