<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for MetadataReference.
 * Generated by PHPUnit on 2011-11-07 at 05:43:20.
 */
class MetadataReferenceTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetadataReference
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetadataReference;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testMimeType() {
    $this->assertFalse($this->object->isset_mimeType());
    
    $value = 'test';
    $this->object->set_mimeType($value);
    $this->assertTrue($this->object->isset_mimeType());
    $this->assertEquals($value, $this->object->get_mimeType());
  }
  
  

  /**
   * 
   */
  public function testVocabularyName() {
    $this->assertFalse($this->object->isset_vocubularyName());
    
    $value = 'test';
    $this->object->set_vocubularyName($value);
    $this->assertTrue($this->object->isset_vocubularyName());
    $this->assertEquals($value, $this->object->get_vocabularyName());
  }
  
   /**
   * 
   */
  public function testInheritedHREF() {
    $this->assertFalse($this->object->isset_href());
    
    $value = 'test';
    $this->object->set_href($value);
    $this->assertTrue($this->object->isset_href());
    $this->assertEquals($value, $this->object->get_href());
  }

}

?>
