<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for MetaDataSection.
 * Generated by PHPUnit on 2011-11-08 at 22:36:42.
 */
class MetaDataSectionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetaDataSection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetaDataSection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testMetadataObject() {
    $this->assertFalse($this->object->isset_metadataObjects());
    
    $value = new MetadataObject();
    $this->object->add_metadataObject($value);
    $this->object->add_metadataObject($value);
    $objs = $this->object->get_metadataObjects();
    
    $this->assertTrue($this->object->isset_metadataObjects());
    $this->assertEquals(2, sizeof($objs));
    $this->assertEquals(get_class($value), get_class($objs[0]));
    
    $this->object->unset_metadataObject();
    $this->assertFalse($this->object->isset_metadataObjects());
  }

}

?>
