<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for PackageHeader.
 * Generated by PHPUnit on 2011-11-02 at 19:26:49.
 */
class PackageHeaderTest extends PHPUnit_Framework_TestCase {

  /**
   * @var PackageHeader
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new PackageHeader;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * tests EnvironmentInfo setter, getter and isset
   */
  public function testEnvironmentInfo() {
    $this->assertFalse($this->object->isset_environmentInfo());

    $envInfo = new EnvironmentInfo();
    $this->object->set_environmentInfo($envInfo);
    $this->assertTrue($this->object->isset_environmentInfo());
    $this->assertEquals('EnvironmentInfo',
            get_class($this->object->get_environmentInfo()),
            'Did not created environementInfo');
  }

  /**
   * Tests volumeInfo setter, getter and isset methods.
   */
  public function testSet_volumeInfo() {
    $this->assertFalse($this->object->isset_volumeInfo());

    $volumeInfo = new VolumeInfo();
    $this->object->set_volumeInfo($volumeInfo);
    $this->assertTrue($this->object->isset_volumeInfo());
    $this->assertEquals('VolumeInfo',
            get_class($this->object->get_volumeInfo()),
            'Did not create volumeInfo');
  }

  /**
   * 
   */
  public function testId() {
    $this->assertFalse($this->object->isset_id());

    $id = 'ID';
    $this->object->set_id($id);
    $this->assertEquals($id, $this->object->get_id());
    $this->assertTrue($this->object->isset_id());
  }

}

?>
