<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for SequenceInformation.
 * Generated by PHPUnit on 2011-11-05 at 03:07:10.
 */
class SequenceInformationTest extends PHPUnit_Framework_TestCase {

  /**
   * @var SequenceInformation
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new SequenceInformation;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * 
   */
  public function testSequencePosition() {
    $this->assertFalse($this->object->isset_sequencePosition());
    
    $value = 10;
    $this->object->set_sequencePosition($value);
    
    $this->assertTrue($this->object->isset_sequencePosition());
    $this->assertEquals($value, $this->object->get_sequencePosition());
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testInvalidSequencePosition() {
    $this->object->set_sequencePosition(-10);
  }
  
  /**
   * 
   */
  public function testSequenceSize() {
    $this->assertFalse($this->object->isset_sequenceSize());
    
    $value = 10;
    $this->object->set_sequenceSize($value);
    
    $this->assertTrue($this->object->isset_sequenceSize());
    $this->assertEquals($value, $this->object->get_sequenceSize());
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testInvalidSequenceSize() {
    $this->object->set_sequenceSize(-10);
  }
  
  /**
   * 
   */
  public function testValue() {
    $this->assertFalse($this->object->isset_value());
    
    $value = 'test';
    $this->object->set_value($value);
    
    $this->assertTrue($this->object->isset_value());
    $this->assertEquals($value, $this->object->get_value());
  }
  
  /**
   * 
   */
  public function testGet_as_DOM() {
    $sequenceSize = 2;
    $sequencePosition = 1;
    $value = 'test';
    
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $expectedElement = $dom->createElement('sequenceInformation');
    $expectedElement->setAttribute('sequenceSize', $sequenceSize);
    $expectedElement->setAttribute('sequencePosition', $sequencePosition);
    $expectedElement->appendChild($dom->createTextNode($value));
    
    $this->object->set_sequencePosition($sequencePosition);
    $this->object->set_sequenceSize($sequenceSize);
    $this->object->set_value($value);
    
    $this->assertEqualXMLStructure($expectedElement, $this->object->get_as_DOM());
  }
  
  /**
   * @expectedException RequiredElementException
   */
  public function testMissingSequenceSize() {
    $this->object->get_as_DOM();
  }
  
  /**
   * @expectedException RequiredElementException
   */
  public function testMissingSequencePosition() {
    $this->object->set_sequenceSize(2);
    $this->object->get_as_DOM();
  }
}

?>
