<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for SequenceInformation.
 * Generated by PHPUnit on 2011-11-05 at 03:07:10.
 */
class SequenceInformationTest extends PHPUnit_Framework_TestCase {

  /**
   * @var SequenceInformation
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new SequenceInformation;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
