<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for VolumeInfo.
 * Generated by PHPUnit on 2011-11-02 at 18:45:18.
 */
class VolumeInfoTest extends PHPUnit_Framework_TestCase {

  /**
   * @var VolumeInfo
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new VolumeInfo;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * Tests proper function of all the sequenceInformation getter, setter and
   * isset methods.
   */
  public function testSequenceInformation() {
    $this->assertFalse($this->object->isset_sequenceInformation());
    
    $value = new SequenceInformation();
    $this->object->set_sequenceInformation($value);
    
    $this->assertTrue($this->object->isset_sequenceInformation());
    $this->assertEquals(get_class($value), get_class($this->object->get_sequenceInformation()));
  }


  /**
   * Tests proper function of specificationVersion getters, setters and isset methods.
   */
  public function testSpecificationVersion() {
    $this->assertEquals(1.0, $this->object->get_specificationVersion());
    $this->assertTrue($this->object->isset_specificationVersion());

    $this->object->set_specificationVersion(1.1);
    $this->assertEquals(1.1, $this->object->get_specificationVersion());

    $this->object->set_specificationVersion(NULL);
    $this->assertFalse($this->object->isset_specificationVersion());
  }
}

?>
