<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/XFDU/xfduPointer.php';

/**
 * Test class for XFDUPointer.
 * Generated by PHPUnit on 2012-03-19 at 17:13:22.
 */
class XFDUPointerTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUPointer
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XFDUPointer;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @todo Implement testGet_as_DOM().
   */
  public function testGet_as_DOM() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
