<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for XFDU.
 * Generated by PHPUnit on 2011-11-04 at 17:35:47.
 */
class XFDUTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDU
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XFDU;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * 
   */
  public function testID() {
    $this->assertFalse($this->object->isset_id());

    $id = 'test';
    $this->object->set_id($id);
    $this->assertTrue($this->object->isset_id());
    $this->assertEquals($id, $this->object->get_id());
  }
  
  /**
   * @expectedException InvalidIDTokenException
   */
  public function testInvalidID() {
    $this->object->set_id('0invalid');
  }

  /**
   * 
   */
  public function testObjID() {
    $this->assertFalse($this->object->isset_objID());

    $objID = 'test';
    $this->object->set_objID($objID);
    $this->assertTrue($this->object->isset_objID());
    $this->assertEquals($objID , $this->object->get_objID());
  }

  /**
   * 
   */
  public function testTextInfo() {
    $this->assertFalse($this->object->isset_textInfo());

    $textInfo = 'test';
    $this->object->set_textInfo($textInfo);
    $this->assertTrue($this->object->isset_textInfo());
    $this->assertEquals($textInfo, $this->object->get_textInfo());
  }

  /**
   * 
   */
  public function testVersion() {
    $this->assertTrue($this->object->isset_version());
    $this->assertEquals(1.0, $this->object->get_version());

    $version = 2.0;
    $this->object->set_version($version);
    $this->assertEquals($version, $this->object->get_version());
  }

  /**
   * 
   */
  public function testPackageHeader() {
    $this->assertFalse($this->object->isset_packageHeader());

    $packageHeader = new PackageHeader();
    $this->object->set_packageHeader($packageHeader);
    $this->assertTrue($this->object->isset_packageHeader());
    $this->assertEquals('PackageHeader', get_class($this->object->get_packageHeader()));
  }

  /**
   * 
   */
  public function testInformationPackageMap() {
    $this->assertFalse($this->object->isset_informationPackageMap());

    $informationPackageMap = new InformationPackageMap();
    $this->object->set_informationPackageMap($informationPackageMap);
    $this->assertTrue($this->object->isset_informationPackageMap());
    $this->assertEquals('InformationPackageMap', get_class($this->object->get_informationPackageMap()));
  }
  
  /**
   * 
   */
  public function testMetadataSection() {
    $this->assertFalse($this->object->isset_metadataSection());

    $value = new MetaDataSection();
    $this->object->set_metadataSection($value);
    $this->assertTrue($this->object->isset_metadataSection());
    $this->assertEquals(get_class($value), get_class($this->object->get_metadataSection()));
  }
  
  /**
   * 
   */
  public function testDataObjectSection() {
    $this->assertFalse($this->object->isset_dataObjectSection());

    $value = new DataObjectSection();
    $this->object->set_dataObjectSection($value);
    $this->assertTrue($this->object->isset_dataObjectSection());
    $this->assertEquals(get_class($value), get_class($this->object->get_dataObjectSection()));
  }
  
  /**
   * 
   */
  public function testBehaviorSection() {
    $this->assertFalse($this->object->isset_behaviorSection());

    $value = new BehaviorSection();
    $this->object->set_behaviorSection($value);
    $this->assertTrue($this->object->isset_behaviorSection());
    $this->assertEquals(get_class($value), get_class($this->object->get_behaviorSection()));
  }
  
  /**
   * A really long test, that probably violates a lot of the rules of unit
   * testing, but ends up being a pretty good test of the overall 
   * document structure.
   */
  public function testDefault_get_as_DOM() {
    // Set the various parameters that will be needed.
    $id = 'test';
    $sequenceSize = 2;
    $sequencePosition = 1;
    $value = 'test';
    
    $dom = new DOMDocument('1.0', 'UTF-8');                                     // create the dom document
    
    // Child of volumeInfo
    $specificationVersion = $dom->createElement('specificationVersion');
    $specificationVersion->appendChild($dom->createTextNode('1.0'));
    
    // Child of volumeInfo
    $sequenceInformation = new SequenceInformation();
    $sequenceInformation->set_sequencePosition($sequencePosition);
    $sequenceInformation->set_sequenceSize($sequenceSize);
    $sequenceInformation->set_value($value);
    
    // Child of packageHeader
    $volumeInfo = new VolumeInfo();
    $volumeInfo->set_sequenceInformation($sequenceInformation);
    
    //Child of environmentInfo
    $xmlData = new XMLData();
    
    //Child of environmentInfo
    $extension = new Extension();
    
    //Child of packageHeader
    $environmentInfo = new EnvironmentInfo();
    $environmentInfo->set_xmlData($xmlData);
    $environmentInfo->set_extension($extension);
    
    //Child of XFDU
    $packageHeader = new PackageHeader();                                       
    $packageHeader->set_id($value);
    $packageHeader->set_volumeInfo($volumeInfo);
    $packageHeader->set_environmentInfo($environmentInfo);
    
    // Root element (XFDU)
    $this->object->set_packageHeader($packageHeader);
    $this->object->set_informationPackageMap(new InformationPackageMap);
    $this->object->set_metadataSection(new MetadataSection());
    $this->object->set_dataObjectSection(new DataObjectSection());
    $this->object->set_behaviorSection(new BehaviorSection());
    
    $dom->appendChild( $dom->importNode($this->object->get_as_DOM(), TRUE) );
    
    
    $this->assertXmlStringEqualsXmlFile(__DIR__.'/files/xfdu-xfdu-test.xml', $dom->saveXML());
  }
  
  /**
   * @expectedException RequiredElementException
   */
  public function testMissingPackageHeader() {
    $this->object->set_packageHeader(new PackageHeader());
    $this->object->get_as_DOM();
  }
  
  /**
   * @expectedException RequiredElementException
   */
  public function testMissingInformationPackageMap() {
    $this->object->get_as_DOM();
  }
  
  /**
   * 
   */
  public function testOtherPrefix_get_as_DOM() {
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $packageHeader = new PackageHeader();
    $packageHeader->set_id('test');
    
    $volumeInfo = new VolumeInfo();
    $packageHeader->set_volumeInfo($volumeInfo);
    
    $this->object->set_packageHeader($packageHeader);
    $this->object->set_informationPackageMap(new InformationPackageMap());
    
    $dom->appendChild($dom->importNode($this->object->get_as_DOM('pre'), TRUE));
    
    $this->assertXmlStringEqualsXmlFile(__DIR__.'/files/pre-xfdu-test.xml', $dom->saveXML());
  }
}

?>
