<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for XMLData.
 * Generated by PHPUnit on 2011-11-07 at 16:53:19.
 */
class XMLDataTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XMLData
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XMLData;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testAnyDOMElement() {
    $this->assertFalse($this->object->isset_any());
    
    $dom = new DOMDocument('1.0', 'UTF-8');
    $value = $dom->createElement('testElement');
    $this->object->set_any($value);
    $this->assertTrue($this->object->isset_any());
    $this->assertEquals($value, $this->object->get_any());
  }
  
  /**
   * 
   */
  public function testAnyDOMNodeList() {
    $this->assertFalse($this->object->isset_any());
    
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $root = $dom->createElement('root');
    $root->appendChild($child1 = $dom->createElement('child1'));
    $root->appendChild($child2 = $dom->createElement('child2'));
    $root->appendChild($child3 = $dom->createElement('child3'));
    $dom->appendChild($root);
    
    // Gets a node list from the document
    $xpath = new DOMXPath($dom);
    $query = '/*';
    $nodeList = $xpath->query($query);
    
    $this->object->set_any($nodeList);
    $this->assertTrue($this->object->isset_any());
    $this->assertEquals($nodeList, $this->object->get_any());
  }
  
  /**
   * 
   */
  public function testGet_as_DOM () {
    $dom = new DOMDocument('1.0', 'UTF-8');
    
    $expectedElement = $dom->createElement('xmlData');
    $expectedElement->appendChild($any = $dom->createElement('stuff'));
    
    $this->object->set_any($any);
    
    $this->assertEqualXMLStructure($expectedElement, $this->object->get_as_DOM(), TRUE);
  }

}

?>
