<?php

require_once dirname(__FILE__) . '/../curation_tool.inc';

/**
 * Test class for AutoloadException.
 * Generated by PHPUnit on 2011-11-05 at 03:06:58.
 */
class AutoloadExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var AutoloadException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new AutoloadException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
