<?php


require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for XFDUPackage.
 * Generated by PHPUnit on 2012-04-16 at 22:57:06.
 */
class XFDUPackageTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $settings = new XFDUSetup();
    $this->object = new XFDUPackage($settings);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }


  /**
   * 
   */
  public function testAddContentUnitNoParent() {
    $dom = new DOMDocument('1.0', 'UTF-8');
    $contentUnit = new ContentUnit();
    
    $this->assertEquals(get_class($contentUnit->get_as_DOM()), get_class($this->object->add($contentUnit)));
    $this->assertEqualXMLStructure($dom->importNode($contentUnit->get_as_DOM(), TRUE), 
            $dom->importNode($this->object->add($contentUnit), TRUE));
  }
  
  /**
   * 
   */
  public function testAddContentUnitWithParent() {
    $parentID = 'parentID';
    $contentUnitParent = new ContentUnit();
    $contentUnitParent->set_id($parentID);
    $this->object->add($contentUnitParent);
    
    $contentUnitChild = new ContentUnit();
    $this->assertEquals(get_class($contentUnitChild->get_as_DOM()), get_class($this->object->add($contentUnitChild, $parentID)));
    
  }

  /**
   * 
   */
  public function testAddDataObject() {
    $dom = new DOMDocument('1.0', 'UTF-8');
    $doID = 'doID';
    
    $dataObject = new DataObject();
    $dataObject->set_id($doID)
            ->add_bytstream(new ByteStream());
    
    $this->assertEqualXMLStructure($dom->importNode($dataObject->get_as_DOM(), TRUE), 
            $dom->importNode($this->object->add($dataObject), TRUE));
  }
  
  /**
   * 
   */
  public function testAddMetadataObject(){
    $dom = new DOMDocument('1.0', 'UTF-8');
    $mdID = 'mdID';
    
    $metadataObject = new MetadataObject();
    $metadataObject->set_id($mdID);
    
    $this->assertEqualXMLStructure($dom->importNode($metadataObject->get_as_DOM(), TRUE), 
            $dom->importNode($this->object->add($metadataObject), TRUE));
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testAddInvalidClass() {
    $contentUnit = new XFDU();
    
    $this->assertTrue($this->object->add($contentUnit));
  }
}

?>
