<?php

require_once dirname(__FILE__) . '/../../../../classes/packages/XFDU/XFDUSetup.php';

/**
 * Test class for XFDUSetup.
 * Generated by PHPUnit on 2011-11-14 at 18:05:45.
 */
class XFDUSetupTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUSetup
   */
  protected $object;
  protected $directory;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XFDUSetup;
    $this->directory = 'temp';
    mkdir($this->directory);
    
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    rmdir($this->directory);
  }

  /**
   * 
   */
  public function testRoot() {
    $this->assertFalse($this->object->isset_root());
    
    $this->object->set_root($this->directory);
    $this->assertTrue($this->object->isset_root());
    $this->assertEquals($this->directory, $this->object->get_root());
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testInvalidRoot() {
    $this->object->set_root('invalid');
  }

}

?>
