<?php

require_once dirname(__FILE__) . '/../../../../classes/packages/xfdu/XFDUBuilder.php';

/**
 * Test class for XFDUBuilder.
 * Generated by PHPUnit on 2012-04-16 at 19:07:04.
 */
class XFDUBuilderTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUBuilder
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XFDUBuilder;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @todo Implement testBuild_xfdu().
   */
  public function testBuild_xfdu() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testBuild_XFDUPointer().
   */
  public function testBuild_XFDUPointer() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
