<?php

require_once dirname(__FILE__) . '/../../../../curation_tool.inc';

/**
 * Test class for XFDUPackage.
 * Generated by PHPUnit on 2012-04-16 at 22:57:06.
 */
class XFDUPackageTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $settings = new XFDUSetup();
    $this->object = new XFDUPackage($settings);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testAddContentUnit() {
    $contentUnit = new ContentUnit();
    
    $dom = new DOMDocument('1.0', 'UTF-8');
    
//    $this->assertTrue($this->object->add($contentUnit));
    $this->assertEquals(get_class($contentUnit->get_as_DOM()), get_class($this->object->add($contentUnit)));
    print get_class($this->object->add($contentUnit));
    $this->assertEqualXMLStructure($dom->importNode($contentUnit->get_as_DOM(), TRUE), 
            $dom->importNode($this->object->add($contentUnit)));
  }
  
  /**
   * @expectedException InvalidArgumentException
   */
  public function testAddInvalidClass() {
    $contentUnit = new XFDU();
    
    $this->assertTrue($this->object->add($contentUnit));
  }

}

?>
