<?php

require_once dirname(__FILE__) . '/../../../../classes/packages/xfdu/XFDUPackage.php';

/**
 * Test class for XFDUPackage.
 * Generated by PHPUnit on 2012-04-04 at 21:30:36.
 */
class XFDUPackageTest extends PHPUnit_Framework_TestCase {

  /**
   * @var XFDUPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new XFDUPackage;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
