<?php

require_once dirname(__FILE__) . '/../../classes/aEnum.php';

/**
 * Test class for aEnum.
 * Generated by PHPUnit on 2011-11-10 at 04:53:50.
 */
class aEnumTest extends PHPUnit_Framework_TestCase {

  /**
   * @var aEnum
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = $this->getMockForAbstractClass('aEnum');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testValues() {
    $this->assertEmpty($this->object->values());
  }

  /**
   * @expectedException InvalidArgumentException
   */
  public function testValue_of() {
    $this->object->value_of('foobar');
  }
  
  public function testHas_value() {
    $this->assertFalse($this->object->has_value('foobar'));
  }

}

?>
