<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/DublinCore/aDCElement.php';

/**
 * Test class for aDCElement.
 * Generated by PHPUnit on 2011-11-16 at 22:01:21.
 */
class aDCElementTest extends PHPUnit_Framework_TestCase {

  /**
   * @var aDCElement
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = $this->getMockForAbstractClass('aDCElement');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testValue() {
    $this->assertFalse($this->object->isset_value());
    
    $value = 'test';
    $this->object->set_value($value);
    
    $this->assertTrue($this->object->isset_value());
    $this->assertEquals($value, $this->object->get_value());
  }

  /**
   * 
   */
  public function testLang() {
    $this->assertFalse($this->object->isset_lang());
    
    $value = 'test';
    $this->object->set_lang($value);
    
    $this->assertTrue($this->object->isset_lang());
    $this->assertEquals($value, $this->object->get_lang());
  }

}

?>
