<?php

require_once dirname(__FILE__) . '/../../../../classes/schemas/DublinCore/Contributor.php';

/**
 * Test class for Contributor.
 * Generated by PHPUnit on 2011-11-16 at 23:57:03.
 */
class ContributorTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Contributor
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Contributor;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  /**
   * 
   */
  public function testPrefixed_get_as_DOM() {
    $value = 'test';
    $prefix = 'pre';
    $dom = new DOMDocument(1.0, 'UTF-8');
    $element = $dom->createElement($prefix.':contributor', $value);
    
    $this->object->set_prefix($prefix);
    
    $this->assertEqualXMLStructure($element, $this->object->get_as_DOM(), TRUE);
  }
  
  /**
   * 
   */
  public function testUnprefixed_get_as_DOM() {
    $value = 'test';
    $dom = new DOMDocument(1.0, 'UTF-8');
    $element = $dom->createElement('contributor', $value);
    
    $this->assertEqualXMLStructure($element, $this->object->get_as_DOM(), TRUE);
  }

}

?>
