<?php

require_once dirname(__FILE__) . '/../../../../../classes/schemas/DublinCore/terms/Abstract.php';

/**
 * Test class for DCAbstract.
 * Generated by PHPUnit on 2011-11-17 at 00:55:05.
 */
class DCAbstractTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DCAbstract
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DCAbstract;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * 
   */
  public function testPrefixed_get_element_as_DOM() {
    $value = 'test';
    $prefix = 'pre';
    $dom = new DOMDocument(1.0, 'UTF-8');
    $element = $dom->createElement($prefix.':abstract', $value);
    
    $this->object->set_prefix($prefix);
    
    $this->assertEqualXMLStructure($element, $this->object->get_element_as_DOM(), TRUE);
  }
  
  /**
   * 
   */
  public function testUnprefixed_get_element_as_DOM() {
    $value = 'test';
    $dom = new DOMDocument(1.0, 'UTF-8');
    $element = $dom->createElement('abstract', $value);
    
    $this->assertEqualXMLStructure($element, $this->object->get_element_as_DOM(), TRUE);
  }

}

?>
