<?php

require_once dirname(__FILE__) . '/../../../../../curation_tool.inc';

/**
 * Test class for CombinationMethod.
 * Generated by PHPUnit on 2011-11-10 at 05:08:49.
 */
class CombinationMethodTest extends PHPUnit_Framework_TestCase {

  /**
   * @var CombinationMethod
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new CombinationMethod;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  public function testValues() {
    $values = $this->object->values();
    
    $this->assertNotEmpty($values);
  }
  
  public function testValue_of() {
    $this->assertEquals('concat', $this->object->value_of('concat'));
  }
  
  public function testHas_value() {
    $this->assertTrue($this->object->has_value('concat'));
  }

}

?>
