<?php

require_once dirname(__FILE__) . '/../../../../../classes/schemas/XFDU/Enums/Locator.php';

/**
 * Test class for Locator.
 * Generated by PHPUnit on 2011-11-10 at 06:04:00.
 */
class LocatorTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Locator
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Locator;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  public function testLocator() {
    $this->assertNotEmpty($this->object->values());
    
    $this->assertEquals('URL', $this->object->value_of('URL'));
    $this->assertEquals('OTHER', $this->object->value_of('OTHER'));
    
    $this->assertTrue($this->object->has_value('URL'));
    $this->assertFalse($this->object->has_value('invalid'));
  }

}

?>
