<?php

require_once dirname(__FILE__) . '/../../../../../classes/schemas/XFDU/Enums/MetadataClassification.php';

/**
 * Test class for MetadataClassification.
 * Generated by PHPUnit on 2011-11-10 at 05:48:20.
 */
class MetadataClassificationTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetadataClassification
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetadataClassification;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  public function testMetadataClassification() {
    $this->assertNotEmpty($this->object->values());
    
    $this->assertTrue($this->object->has_value('DED'));
    $this->assertTrue($this->object->has_value('FIXITY'));
    
    $this->assertFalse($this->object->has_value('invalid'));
    
    $this->assertEquals('SYNTAX', $this->object->value_of('SYNTAX'));
    $this->assertEquals('REFERENCE', $this->object->value_of('REFERENCE'));
  }

}

?>
