<?php

require_once dirname(__FILE__) . '/../../../../../classes/schemas/XFDU/Enums/MetadataCategory.php';

/**
 * Test class for MetadataCategory.
 * Generated by PHPUnit on 2012-03-19 at 17:14:01.
 */
class MetadataCategoryTest extends PHPUnit_Framework_TestCase {

  /**
   * @var MetadataCategory
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new MetadataCategory;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
