<?php

/**
 * Primary module for the curatoin tool package which serves as a front end for
 * the data curation class libarary.
 * 
 * @author Robert Olendorf
 * @license Apache Licesnse 2.0 
 */

function curation_tool_help($path, $arg) {
  if($path == 'admin/help/#curation_tool') {
    return t('A drupal frontend for the data curation library.');
  }
}

function curation_tool_permission() {
  return array(
      'create any project' => array(
          'title' => t('Create any project'),
          'description' => t('Create a project for any account'),
          'frestricted access' => TRUE,
      ),
      'create own project' => array(
          'title' => t('Create own project'),
      ),
      'delete any project' => array(
          'title' => t('Delete any project'),
          'description' => t('Delete a project from any account'),
          'frestricted access' => TRUE,
      ),
      'delete own project' => array(
          'title' => t('Delete own projects'),
          'description' => t('Delete a project from a user&apos;s own account'),
      ),
      'edit any project' => array(
          'title' => t('Edit any project'),
          'description' => t('Edit projects from any account'),
          'frestricted access' => TRUE,
      ),
      'edit own project' => array(
          'title' => t('Edit own projects'),
          'description' => t('Edit a project from a user&apos;s own account'),
      ),
  );
}

?>