<?php

require_once dirname(__FILE__) . '/../../../classes/packages/DummyPackage.php';

/**
 * Test class for DummyPackage.
 * Generated by PHPUnit on 2011-11-05 at 03:07:02.
 */
class DummyPackageTest extends PHPUnit_Framework_TestCase {

  /**
   * @var DummyPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new DummyPackage;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

}

?>
